### PR TITLE
added Cosmos DB guidance

### PR DESCRIPTION
**Pull request by kovarikthomas**
# Overview/Summary

This PR adds service guidance for Azure Cosmos DB. The guidance has been reviewed and approved by engineering.

Related ADO item id: 27706

## This PR fixes/adds/changes/removes

1. Adds service guidance for Azure Cosmos DB

### Breaking Changes

None

## As part of this Pull Request I have

- [X] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [X] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [X] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [X] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [ ] Ensured PR tests are passing
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Comment by lachaves** [comment]
@kovarikthomas, can you please fix some "Wrong line endings" and "Trailing whitespace" errors reported by lint code check.

**Comment by kovarikthomas** [comment]
@lachaves That's done, all linting checks are passing now.

**Comment by lachaves** [comment]
@kovarikthomas, I was able to run hugo server and validate content and links. 
The only thing we need to change is the State, as we are using only Preview for now (not using Verified for now). Can you please change the state for all from Verified to Preview so we can approve, merge and close?

**Comment by kovarikthomas** [comment]
@lachaves I have reverted all states to preview. Please approve and merge. Thanks!

**Review by lachaves — APPROVED** [review]
Ran hugo server, validated links, content, looks good to me.

**Pull request merged**
