### PR TITLE
Add new guidance item ERGW-6 for customer controlled maintenance 

### PR DESCRIPTION
**Pull request by ehaslett**
# Overview/Summary

Adds new guidance for ExR VNG customer controlled maintenance

## Related Issues/Work Items

AB#33035

## This PR fixes/adds/changes/removes

1. Guidance for ERGW-6 for ExR VNG customer controlled maintenance
2. Moves old ERGW-6 to ERGW-7

## As part of this Pull Request I have

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [x] Ensured PR tests are passing
- [x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Comment by ehaslett** [comment]
Not sure the linking issue:
https://dev.azure.com/CSUSolEng/Azure%20Infra%20Networking/_workitems/edit/33035/

**Review by khushal08 — APPROVED** [review]
LGTM

**Review by ejhenry — COMMENTED** [review]
@ehaslett we are no longer changing or reusing recommendation IDs. Can you leave ERGW-6 as is and use ERGW-7 for the new recommendation? This is a new requirement, so not yet in the contribution guide. Apologies for the inconvenience.

**Comment by ehaslett** [comment]
> @ehaslett we are no longer changing or reusing recommendation IDs. Can you leave ERGW-6 as is and use ERGW-7 for the new recommendation? This is a new requirement, so not yet in the contribution guide. Apologies for the inconvenience.

I changed the order to maintain highest impact to lowest impact (new ERGW-6 > ERGW-7 [old ERGW-6]). So even if not numbered/ID'ed, I'd still be re-ordering them. Thoughts?

**Comment by ejhenry** [comment]
> > @ehaslett we are no longer changing or reusing recommendation IDs. Can you leave ERGW-6 as is and use ERGW-7 for the new recommendation? This is a new requirement, so not yet in the contribution guide. Apologies for the inconvenience.
> 
> I changed the order to maintain highest impact to lowest impact (new ERGW-6 > ERGW-7 [old ERGW-6]). So even if not numbered/ID'ed, I'd still be re-ordering them. Also - the WARA guidance and the remediation guidance also match the re-ordering to maintain high -> low. Thoughts? Is the high -> low ordering a standard? If not, should it be?

The high to low ordering is not a standard we're using in APRL. At present it is merely a unique identifier for the recommendation. Changing the IDs is a problem for downstream systems that consume from APRL.

**Comment by ehaslett** [comment]
Closing- will resubmit to leave ERGW-6 as is, and add the new guidance as ERGW-7

**Pull request closed without merging**
