### PR TITLE
Fixed 31313 and 31314

### PR DESCRIPTION
**Pull request by khushal08**
[AB#31313](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/31313) AFD-1 query should only return results if there is a mix of AFD and TM
[AB#31314](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/31314) AFD-10 Query is looking for incorrect type. Type should be: "microsoft.network/frontdoorwebapplicationfirewallpolicies"

### CODE REVIEW

**Comment by khushal08** [comment]
@ejhenry Creating PR as discussed with only changes for following:
[AB#31313](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/31313) AFD-1 query should only return results if there is a mix of AFD and TM
[AB#31314](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/31314) AFD-10 Query is looking for incorrect type. Type should be: "microsoft.network/frontdoorwebapplicationfirewallpolicies"

**Review by ejhenry — COMMENTED** [review]
Thanks for the contribution @khushal08. Please include a screenshot of your test results for the AFD-10 query.

**Comment by ejhenry** [comment]
@Azure/aprl-networking please review and compare with #319

**Comment by ejhenry** [comment]
@Azure/aprl-networking please review

**Comment by oZakari** [comment]
@JefferyMitchel based upon @DaFitRobsta's feedback are we okay to close?

**Review by JefferyMitchell — APPROVED** [review]

**Review by rodrigosantosms — APPROVED** [review]
approved.

**Comment by rodrigosantosms** [comment]
PR #319 fixed these issues. closing this PR.

**Pull request closed without merging**
