### PR TITLE
Fixed KQL bugs (31313, 31314, 31315)

### PR DESCRIPTION
**Pull request by khushal08**
# Overview/Summary

Fixes several networking services bugs

## Related Issues/Work Items

[AB#31313](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/31313) AFD-1 query should only return results if there is a mix of AFD and TM
[AB#31314](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/31314) AFD-10 Query is looking for incorrect type. Type should be: "microsoft.network/frontdoorwebapplicationfirewallpolicies"
[AB#31315](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/31315) AFD-11 - Query is returning WAFs that are configured correctly. Should return those that are not.

## This PR fixes/adds/changes/removes

[AB#31313](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/31313) AFD-1 query should only return results if there is a mix of AFD and TM
[AB#31314](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/31314) AFD-10 Query is looking for incorrect type. Type should be: "microsoft.network/frontdoorwebapplicationfirewallpolicies"
[AB#31315](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/31315) AFD-11 - Query is returning WAFs that are configured correctly. Should return those that are not.
### Breaking Changes

1. None

## As part of this Pull Request I have

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [x] Ensured PR tests are passing
- [x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Comment by oZakari** [comment]
Hi @khushal08, could you please add screenshots showing the output for the queries? Also, you can remove the query files suffixed with .fix as those were just to be used as a starting point.

**Review by ejhenry — COMMENTED** [review]
Thanks for the contribution @khushal08!

For AFD-1 we will want to have a KQL file. If the recommendation cannot be validated with ARG, we should include the recommended content from the contribution guide for this scenario.

For AFD-11, I think this recommendation is too generic and should be removed entirely.  Thoughts? cc: @rodrigosantosms, @oZakari

**Comment by oZakari** [comment]
> Thanks for the contribution @khushal08!
> 
> For AFD-1 we will want to have a KQL file. If the recommendation cannot be validated with ARG, we should include the recommended content from the contribution guide for this scenario.
> 
> For AFD-11, I think this recommendation is too generic and should be removed entirely. Thoughts? cc: @rodrigosantosms, @oZakari

@ejhenry com - Completely, agree that it's too generalized and should be removed.

**Comment by ejhenry** [comment]
> > Thanks for the contribution @khushal08!
> > For AFD-1 we will want to have a KQL file. If the recommendation cannot be validated with ARG, we should include the recommended content from the contribution guide for this scenario.
> > For AFD-11, I think this recommendation is too generic and should be removed entirely. Thoughts? cc: @rodrigosantosms, @oZakari
> 
> I will remove AFD-11. I will add KQL file for AFD-1. However, there is no KQL to validate this. Can you please explain what you mean by "e should include the recommended content from the contribution guide for this scenario."?

Thanks @khushal08. This section of the contribution guide covers the expected content for the kql files when the query is still under development or there is no possible query.

https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing/#azure-resource-graph-arg-queries

**Comment by khushal08** [comment]
> Hi @khushal08, could you please add screenshots showing the output for the queries? Also, you can remove the query files suffixed with .fix as those were just to be used as a starting point.

Hi @oZakari I have removed the .fix file.

**Comment by khushal08** [comment]
> > > Thanks for the contribution @khushal08!
> > > For AFD-1 we will want to have a KQL file. If the recommendation cannot be validated with ARG, we should include the recommended content from the contribution guide for this scenario.
> > > For AFD-11, I think this recommendation is too generic and should be removed entirely. Thoughts? cc: @rodrigosantosms, @oZakari
> > 
> > 
> > I will remove AFD-11. I will add KQL file for AFD-1. However, there is no KQL to validate this. Can you please explain what you mean by "e should include the recommended content from the contribution guide for this scenario."?
> 
> Thanks @khushal08. This section of the contribution guide covers the expected content for the kql files when the query is still under development or there is no possible query.
> 
> https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing/#azure-resource-graph-arg-queries

Hi @ejhenry I have pushed the latest changes incorporating feedback.

**Comment by ejhenry** [comment]
@khushal08 - it looks as though there were changes made to the AFD recommendations recently that are resulting in some confusion with this PR. The AFD-11 recommendation we were discussing previously has already been removed. I recommend reviewing the current AFD recommendations in APRL to determine specifically what changes are still needed.

**Comment by ejhenry** [comment]
Closing PR per conversation with @khushal08. A new PR will be submitted for necessary changes.

**Pull request closed without merging**
