### PR TITLE
fixed vnet-3 query

### PR DESCRIPTION
**Pull request by ReneHezser**
# Overview/Summary

Adjusted to match requirements

## Related Issues/Work Items

[AB#32812](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/32812)

## As part of this Pull Request I have

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [x] Ensured PR tests are passing
- [x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Comment by ejhenry** [comment]
Thanks @ReneHezser. Please include screenshots of the output of your query in the PR.

**Comment by ReneHezser** [comment]
**vnet-3**
image

**Comment by oZakari** [comment]
Hi @ReneHezser, I think we probably need to change the scope of the resources found to only list subnets that have service endpoints configured for services that do support private link. Otherwise, we are going to get some frustrated customers once this gets published to Azure Advisor.

**Comment by ehaslett** [comment]
> Hi @ReneHezser, I think we probably need to change the scope of the resources found to only list subnets that have service endpoints configured for services that do support private link. Otherwise, we are going to get some frustrated customers once this gets published to Azure Advisor.
> 
> @Azure/aprl-networking please provide your perspectives as well.

I agree with removing any Azure resource that has only Service Endpoint as an option.

**Comment by ReneHezser** [comment]
> > Hi @ReneHezser, I think we probably need to change the scope of the resources found to only list subnets that have service endpoints configured for services that do support private link. Otherwise, we are going to get some frustrated customers once this gets published to Azure Advisor.
> > @Azure/aprl-networking please provide your perspectives as well.
> 
> I agree with removing any Azure resource that has only Service Endpoint as an option.

The recommendation is now checking against the known ServiceEndpoints https://learn.microsoft.com/en-us/azure/virtual-network/virtual-network-service-endpoints-overview
image

**Review by oZakari — APPROVED** [review]
Thanks for adjusting the query @ReneHezser!

**Comment by ReneHezser** [comment]
> Thanks for adjusting the query @ReneHezser!

The suggestion made sense ;-)

**Comment by ejhenry** [comment]
Perhaps I'm misunderstanding, but I don't see where the query is filtering out the service endpoints configured for services that do not support private link,

cc @oZakari @ehaslett

**Comment by ehaslett** [comment]
> Perhaps I'm misunderstanding, but I don't see where the query is filtering out the service endpoints configured for services that do not support private link,
> 
> cc @oZakari @ehaslett

I am wondering if line 11 in the screen capture, where the resource names are enumerated, is where this is being done. Essentially hardcoding the list of resources that support both SE and PE, and if there is an SE that matches, this should be called out, so this could be noted for remediation. @ReneHezser - is this the approach being used in the query?

**Comment by ReneHezser** [comment]
> > Perhaps I'm misunderstanding, but I don't see where the query is filtering out the service endpoints configured for services that do not support private link,
> > cc @oZakari @ehaslett
> 
> I am wondering if line 11 in the screen capture, where the resource names are enumerated, is where this is being done. Essentially hardcoding the list of resources that support both SE and PE, and if there is an SE that matches, this should be called out, so this could be noted for remediation. @ReneHezser - is this the approach being used in the query?

@ehaslett you are right. The available services with Service Endpoints are documented [here](https://learn.microsoft.com/en-us/azure/virtual-network/virtual-network-service-endpoints-overview). Filtering by a hard-coded list seems to be OK for me, as there probably will not be changes to this list.

@oZakari if a subnet has an endpoint enabled that offers Private Link, the query will report them.

**Comment by ejhenry** [comment]
> > > Perhaps I'm misunderstanding, but I don't see where the query is filtering out the service endpoints configured for services that do not support private link,
> > > cc @oZakari @ehaslett
> > 
> > 
> > I am wondering if line 11 in the screen capture, where the resource names are enumerated, is where this is being done. Essentially hardcoding the list of resources that support both SE and PE, and if there is an SE that matches, this should be called out, so this could be noted for remediation. @ReneHezser - is this the approach being used in the query?
> 
> @ehaslett you are right. The available services with Service Endpoints are documented [here](https://learn.microsoft.com/en-us/azure/virtual-network/virtual-network-service-endpoints-overview). Filtering by a hard-coded list seems to be OK for me, as there probably will not be changes to this list.
> 
> @oZakari if a subnet has an endpoint enabled that offers Private Link, the query will report them.

So the static list contains the services that support both SE and PE? The list looks the same as the list of SE services. Are there any services that support SE that don't support PE?

**Comment by ReneHezser** [comment]
> So the static list contains the services that support both SE and PE? The list looks the same as the list of SE services. Are there any services that support SE that don't support PE?

That is correct. As of https://learn.microsoft.com/en-us/azure/private-link/availability and https://learn.microsoft.com/en-us/azure/virtual-network/virtual-network-service-endpoints-overview the inner join is in the query.

~~Cosmos DB is in the list of service endpoints, but private link is not available.~~ Scratch that. I missed it.

**Review by ehaslett — APPROVED** [review]
LGTM

**Pull request merged**
