### PR TITLE
New azure backup RSV cross region restore recommendation

### PR DESCRIPTION
**Pull request by alisakina99**
# Overview/Summary

Enable cross region restore. This option allows you to conduct drills to meet audit or compliance requirements, and to restore the VM or its disk if there's a disaster in the primary region. 

## Related Issues/Work Items

[AB#29821](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/29821)

## This PR fixes/adds/changes/removes

1. bk-2.kql
2. index.md

## As part of this Pull Request I have

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [x] Ensured PR tests are passing
- [x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

bk-2

### CODE REVIEW

**Review by oZakari — APPROVED** [review]
LGTM 👍🏼

**Review by oZakari — CHANGES_REQUESTED** [review]
Can you please add bk-2 to the table?

**Review by oZakari — APPROVED** [review]
LGTM

**Review by ejhenry — APPROVED** [review]
LGTM 👍

**Pull request merged**
