### PR TITLE
vm-20 - Ensure VM Extensions per OS Type

### PR DESCRIPTION
**Pull request by ReneHezser**
# Overview/Summary

Ensure VM Extension are installed and distinguish between the OS Type

## Related Issues/Work Items

[AB#32795](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/32795)
#196 

### Breaking Changes

none

## As part of this Pull Request I have

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [x] Ensured PR tests are passing
- [x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Comment by ReneHezser** [comment]
**vm-20**
image

**Comment by ejhenry** [comment]
Thanks @ReneHezser. Per this bug (https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues/196) I think we may need additional validation steps in the query. Do you want to follow-up with @tksh164 to develop the query further?

**Comment by ReneHezser** [comment]
> Thanks @ReneHezser. Per this bug (#196) I think we may need additional validation steps in the query. Do you want to follow-up with @tksh164 to develop the query further?

Thanks @ejhenry I'll work with Takeshi on this

**Comment by oZakari** [comment]
Hey @ReneHezser, when you are ready for a review, feel free to just add me as a review please.

**Pull request closed without merging**
