### PR TITLE
update to TRAF-2

### PR DESCRIPTION
**Pull request by davenewman777**
# Overview/Summary

Update to TRAF-2

## Related Issues/Work Items

https://dev.azure.com/CSUSolEng/Azure%20Infra%20Networking/_workitems/edit/34206
## This PR fixes/adds/changes/removes

Fix for TRAF-2

### Breaking Changes

None

## As part of this Pull Request I have

- [x ] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [x ] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [x ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [ x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [x ] Ensured PR tests are passing
- [ x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- [x ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)
TRAF-2

### CODE REVIEW

**Comment by davenewman777** [comment]
related work item is technically https://dev.azure.com/CSUSolEng/Azure%20Infra%20Networking/_workitems/edit/34275/ which was created from https://dev.azure.com/CSUSolEng/Azure%20Infra%20Networking/_workitems/edit/34206

**Comment by ejhenry** [comment]
PR #329 also in review has a TRAF-2 query. Can we close this PR as duplicate?

**Review by ehaslett — CHANGES_REQUESTED** [review]
As Eric mentioned, I think this query has already been completed just a few days ago, and is almost identical. However, I like that this one has a parameter that spells out the issue (only 1 endpoint), so I'd recommend pulling down the now existing query, and update it. I'd recommend changing the wording to "fewer than 2 endpoints" since this would also cover a case where the endpoint count is 0, as per the now existing ARG query. Thank you for the work on this!

**Comment by ejhenry** [comment]
Closing as this PR is a duplicate of #329 which has been merged.

**Pull request closed without merging**
