### PR TITLE
Jimays avila patch 1 vmss main md and kql

### PR DESCRIPTION
**Pull request by jimays-avila**
# Overview/Summary

Updated VMSS main md file and kql to include additional recommendations

## Related Issues/Work Items

[AB#29814](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/29814)

## This PR fixes/adds/changes/removes

1. Updated main vmss md file with vmss-10 and vmss11 recommendations
2. Added KQL for vmss-11 (vmss-10 was added previously while main md was not for some reason.)

## As part of this Pull Request I have

- [ ] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [ ] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [ ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [ ] Ensured PR tests are passing
- [ ] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Review by ejhenry — COMMENTED** [review]
@jimays-avila - Can you update the vmss-10.kql query to only return results that do not match the recommendation? The current query format does not align with that standard.

For the vmss-10.kql query, are you able to limit the results to only VMs attached to VMSS instances? It's not clear how the current query is different from the query for VM-8. Additionally, the query looks like it is only evaluating OS disks.

**Comment by ejhenry** [comment]
> @ejhenry I can check vmss-10 but this PR does not contain changes to VMSS-10 KQL.

@jimays-avila This PR contains a VMSS-10 recommendation and links to the ARG query. The ARG query, which you authored in a prior PR, needs to conform to the standard of only returning the resources that do not align to the recommendation. Thanks.

**Comment by jimays-avila** [comment]
@ejhenry I have fixed the query. Would you like to resubmit my PR to include that fix or just submit another one for the KQL fix

**Comment by ejhenry** [comment]
> @ejhenry I have fixed the query. Would you like to resubmit my PR to include that fix or just submit another one for the KQL fix

@jimays-avila - For VMSS-10, shouldn't the query be identifying VMSS instances running on images that have been scheduled for deprecation?

**Comment by jimays-avila** [comment]
> > @ejhenry I have fixed the query. Would you like to resubmit my PR to include that fix or just submit another one for the KQL fix
> 
> @jimays-avila - For VMSS-10, shouldn't the query be identifying VMSS instances running on images that have been scheduled for deprecation?

@ejhenry this was one of the recommendations added by someone else as missing for VMSS and I added it based on the information they listed.  If you believe this would be a better fit for APRL I can attempt to rewrite the query based on what you stated.

**Comment by ejhenry** [comment]
> > > @ejhenry I have fixed the query. Would you like to resubmit my PR to include that fix or just submit another one for the KQL fix
> > 
> > 
> > @jimays-avila - For VMSS-10, shouldn't the query be identifying VMSS instances running on images that have been scheduled for deprecation?
> 
> @ejhenry this was one of the recommendations added by someone else as missing for VMSS and I added it based on the information they listed. If you believe this would be a better fit for APRL I can attempt to rewrite the query based on what you stated.

Thanks @jimays-avila. I read VMSS-10 to be recommending that deprecated images should not be used, so I think we want the ARG query to identify VMSS instances running on images that have been scheduled for deprecation.

**Comment by jimays-avila** [comment]
> > > > @ejhenry I have fixed the query. Would you like to resubmit my PR to include that fix or just submit another one for the KQL fix
> > > 
> > > 
> > > @jimays-avila - For VMSS-10, shouldn't the query be identifying VMSS instances running on images that have been scheduled for deprecation?
> > 
> > 
> > @ejhenry this was one of the recommendations added by someone else as missing for VMSS and I added it based on the information they listed. If you believe this would be a better fit for APRL I can attempt to rewrite the query based on what you stated.
> 
> Thanks @jimays-avila. I read VMSS-10 to be recommending that deprecated images should not be used, so I think we want the ARG query to identify VMSS instances running on images that have been scheduled for deprecation.

@ejhenry I will work on that.

**Comment by jimays-avila** [comment]
> @jimays-avila no rush or anything, but when you're ready for us to review, please feel free to request a review from us at the top right.

@oZakari I will work on this query this week.

**Comment by jimays-avila** [comment]
> @jimays-avila the command you issued was incorrect. Please try again.
> 
> Examples are:
> 
> ```
> @ agree
> ```
> 
> and
> 
> ```
> @ agree company="your company"
> ```

**Pull request closed without merging**
