### PR TITLE
Added Azure Resource Graph Query for VM-20

### LINKED ISSUE #196: 🪲 Bug Report - VM-20: Return incorrect result
## Describe the bug

The [VM-20 query](https://azure.github.io/Azure-Proactive-Resiliency-Library/services/compute/virtual-machines/#vm-20---enable-vm-insights) returns incorrect result. Because the VM extension installation state does not represent VM insights enabled, or not. 

## To Reproduce

1. Deploy an Azure Windows VM.
2. [Install `AzureMonitorWindowsAgent` extension](https://learn.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-manage#install) to the deployed Azure Windows VM.

The query result does not have the deployed Azure Windows VM even though VM insights is not enabled.

## Expected behavior

The query returns the correct result.

## Screenshots 📷

1. **Not enabled** VM insights on `vm6`, and it have the `AzureMonitorWindowsAgent` VM extension.

    image
    
    image

    image

    image

2. The query result does not have `vm6` even though VM insights is **not enabled**. (The result should include vm6 because VM insights is not enabled on the VM)

    image

## Additional context

None

### PR DESCRIPTION
**Pull request by Pla5ma**
# Overview/Summary

Fixes #196 

1. Added Azure Resource Graph Query for VM-20.
2. Corrected a typo for VM-13 ARG Query Available state. It was No but a query is available.

## This PR fixes/adds/changes/removes

1. docs\content\services\compute\virtual-machines\code\vm-20\vm-20.kql

image

2. docs\content\services\compute\virtual-machines\_index.md

## As part of this Pull Request I have

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [x] Ensured PR tests are passing
- [x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Review by Dost2010 — APPROVED** [review]

**Comment by Pla5ma** [comment]
Added a typo change for VM-13 ARG Query Available state.

**Comment by oZakari** [comment]
Linking to #196.

**Comment by oZakari** [comment]
Looking back at #196, looks like there are still some remaining considerations to take into account before we can approve this PR as is. 

cc: @tksh164 @ReneHezser

**Review by tksh164 — COMMENTED** [review]
The query needs additional consideration about the following case:

- AzureMonitorWindowsAgent installed, but not yet enabled VM insights. The query result does not cover this case.
- VM insights enabled with MicrosoftMonitoringAgent. The query result included this case even if enabled VM insights.

Please see #196 for details. Also, [a test case for VM-20](https://github.com/tksh164/aprl-testing/tree/main/services/compute/virtual-machines/test/vm-20) will help you.

**Comment by Pla5ma** [comment]
> The query needs additional consideration about the following case:
> 
> * AzureMonitorWindowsAgent installed, but not yet enabled VM insights. The query result does not cover this case.
You are right. What do you think about:

```
Resources
| where type == 'microsoft.compute/virtualmachines'
| project idVm = tolower(id), name, tags
| join kind=leftouter (
    InsightsResources
    | where type =~ "Microsoft.Insights/dataCollectionRuleAssociations" and id has "Microsoft.Compute/virtualMachines"
    | project idDcr = tolower(properties.dataCollectionRuleId), idVmDcr = tolower(substring(id, 0, indexof(id, "/providers/Microsoft.Insights/dataCollectionRuleAssociations/"))))
on $left.idVm == $right.idVmDcr
| join kind=leftouter (
    Resources
    | where type =~ "Microsoft.Insights/dataCollectionRules"
    | extend
        isPerformanceEnabled = iif(properties.dataSources.performanceCounters contains "Microsoft-InsightsMetrics" and properties.dataFlows contains "Microsoft-InsightsMetrics", true, false),
        isMapEnabled = iif(properties.dataSources.extensions contains "Microsoft-ServiceMap" and properties.dataSources.extensions contains "DependencyAgent" and properties.dataFlows contains "Microsoft-ServiceMap", true, false)//,
    | where isPerformanceEnabled or isMapEnabled 
    | project dcrName = name, isPerformanceEnabled, isMapEnabled, lowerCaseDcrId = tolower(id))
on $left.idDcr == $right.lowerCaseDcrId
| join kind=leftouter (
    Resources
        | where type == 'microsoft.compute/virtualmachines/extensions' and (name contains 'AzureMonitorWindowsAgent' or name contains 'AzureMonitorLinuxAgent')
        | extend idVmExtension = tolower(substring(id, 0, indexof(id, '/extensions'))), extensionName = name)
on $left.idVm == $right.idVmExtension
| where isPerformanceEnabled != 1 or (extensionName != 'AzureMonitorWindowsAgent' and extensionName != 'AzureMonitorLinuxAgent') or idDcr == ''
| project recommendationId = "vm-20", name, id = idVm, tags, monitoringExtension = extensionName, isPerformanceEnabled, dataCollectionRuleId = idDcr
```
It shows VMs if:
Azure Monitoring Agent (Windows or Linux) is missing OR
isPerformanceEnabled is not enabled OR
DCR is not linked

> * VM insights enabled with MicrosoftMonitoringAgent. The query result included this case even if enabled VM insights.
Other agents will be deprecated in August. So I think we can exclude them already.

**Review by oZakari — APPROVED** [review]
I think it looks good to me at this point, thank you @Pla5ma! 

Will merge if @tksh164 is okay with the changes.

**Review by tksh164 — APPROVED** [review]
Looks good to me.

> > - VM insights enabled with MicrosoftMonitoringAgent. The query result included this case even if enabled VM insights.

> Other agents will be deprecated in August. So I think we can exclude them already.

MicrosoftMonitoringAgent is will be deprecated. So, APRL should find it if customers are still using the deprecated agents because APRL provides information that which resources do not adhere to recommendations, I believe.

However, the monitoring agent deprecation can be checked with another recommendation.

**Pull request merged**
