### PR TITLE
Update: Remove PowerShell/CLI references and hide scripts

### PR DESCRIPTION
**Pull request by oZakari**
# Overview/Summary

As requested by leadership, we are removing the PowerShell and Azure CLI script references within the guidance and service recommendation pages. Leaving the existing scripts in place, but hiding them from public view in case we need to reference them in the future.

## Related Issues/Work Items

Replace this with a list of related GitHub Issues and/or ADO Work Items (Internal Only)

N/A

## This PR fixes/adds/changes/removes

1. Removes guidance/ pertaining to Azure CLI and PowerShell
2. Hides PowerShell and Azure CLI scripts while also replacing with KQL file.

### Breaking Changes

1. None

## As part of this Pull Request I have

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [x] Ensured PR tests are passing
- [x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Review by ejhenry — APPROVED** [review]
Thanks @oZakari! LGTM 👍

**Comment by DaFitRobsta** [comment]
@oZakari, looks like there are conflicts. Can you please review.
Thanks!

**Comment by oZakari** [comment]
Thanks @DaFitRobsta, I have fixed the merge conflicts. Please approve if you are okay with the updates and if any other PRs come in ahead of mine, I will just fix any conflicts before merging.

**Review by DaFitRobsta — APPROVED** [review]
LGTM 👍

**Comment by DaFitRobsta** [comment]
@Azure/aprl-hpc, please review.
Thank you

**Pull request merged**
