### PR TITLE
Update VM-5 guidance and resources

### PR DESCRIPTION
**Pull request by pinyuko**
# Overview/Summary
Update VM-5 Guidance and Resources.
Previous guidance is not clear on why customer should use managed disk. Updated that with EoS info.

## Related Issues/Work Items

Replace this with a list of related GitHub Issues and/or ADO Work Items (Internal Only)

- To associate a GitHub Issue, use a [key word](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) preceded with the GitHub issue number.
- To associate an ADO Work Item, use the key word `AB#` succeeded with the [ADO Work Item ID](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## This PR fixes/adds/changes/removes

1. Update "VM-5 - Use Managed Disks for VM disks" Guidance and Resources.
Previous guidance is not clear on why customer should use managed disk. Updated that with EoS info.

### Breaking Changes

N/A

## As part of this Pull Request I have

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [x] Ensured PR tests are passing
- [x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Review by ejhenry — COMMENTED** [review]
Thanks @pinyuko, the updated guidance looks good. The broken AKS link has been fixed in another PR. Can you please resolve your merge conflict? Happy to help resolve if needed.

**Comment by pinyuko** [comment]
Thanks @ejhenry ! Removed the AKS one. Please re-review and approve. Thanks!

**Review by oZakari — APPROVED** [review]
LGTM

**Review by ejhenry — APPROVED** [review]
LGTM 👍

**Pull request merged**
