### PR TITLE
Fix ST-3 query

### PR DESCRIPTION
**Pull request by tksh164**
# Overview/Summary

Fixed ST-3 query. The fixed query returns all storage accounts that upgradeable to General purpose v2.

**Note 1**: The guidance of ST-3 is unclear. Because Performance tier means Standard or Premium. It is just a choice; one is not better than the other. Also, block blob, append blob and page blob are types of blobs, not related to performance tier. In addition, file share is storage of file service, it does not compare with blob service.

- https://azure.github.io/Azure-Proactive-Resiliency-Library/services/storage/storage-account/#st-3---ensure-performance-tier-is-set-as-per-workload
    > **Guidance**
    > Consider using appropriate storage performance tier for standard storage / block blob / append blob / file-share and page blob. Each workload scenario requires appropriate Performance tier and its important that based on the type of transaction and blob type/file type appropriate performance tier is selected. Failing to do so will create performance bottleneck.

**Note 2**: Access tier is related to cost (& time to first byte), not storage performance.

- [Access tiers for blob data](https://learn.microsoft.com/en-us/azure/storage/blobs/access-tiers-overview)

## Related Issues/Work Items

- #297

## This PR fixes/adds/changes/removes

1. Fixes ST-3 query.
2. Updates links in Resources section.

### Breaking Changes

None

## As part of this Pull Request I have

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [ ] Ensured PR tests are passing
- [x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

## Screenshot

- [Test case](https://github.com/tksh164/aprl-testing/tree/main/services/storage/storage-account/test/st-3)

image

### CODE REVIEW

**Comment by ejhenry** [comment]
Thanks @tksh164 and agree the guidance for ST-3 is not clear or actionable. The same is true for ST-4. Perhaps we should just remove both recommendations entirely?

**Comment by oZakari** [comment]
@tksh164 To reflect and use your query, we could add a new recommendation to upgrade your storage account if using Blob Storage since that should be separate from the Classic Storage account sku. We can then delete 3/4 as @ejhenry suggested if you agree?

**Comment by tksh164** [comment]
@ejhenry @oZakari - Sorry for late response. I agree with @ejhenry suggestion. And I suggest adding "Upgrade legacy storage accounts to v2 storage accounts" as a new recommendation.

**Comment by tksh164** [comment]
I will create PRs for delete ST-3 & ST-4 and for a new recommendation.

**Pull request closed without merging**
