### PR TITLE
Updating the virtual network guidelines

### PR DESCRIPTION
**Pull request by maheshbenke**
# Overview/Summary

Updating the virtual network guidelines for Resiliency.
1. *Added Guidance for VNET*

### Breaking Changes

1. NA

## As part of this Pull Request I have

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [x] Ensured PR tests are passing
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Comment by maheshbenke** [comment]
:)

**Comment by maheshbenke** [comment]
Reopening the PR with Fixed Code.

**Comment by maheshbenke** [comment]
Updated the naming convention as requested.

**Review by rodrigosantosms — APPROVED** [review]
approved

**Pull request merged**
