### PR TITLE
US 32392 Fix Queries for AFD 1 AFD 10 and AFD 11

### PR DESCRIPTION
**Pull request by didayal-msft**
# Overview/Summary

Replace this with a brief description of what this Pull Request fixes, changes, etc.

## Related Issues/Work Items

AB#32392 Azure Front Door - APRL ARG Query Quality Improvement

## This PR fixes/adds/changes/removes

AFD-1 - Avoid combining Traffic Manager and Front Door

This query lists out all traffic manager profiles where endpoint target value is equal to the azure front door endpoint name or azure front door custom domain name.

This works on the premise that traffic manager and front door can only be combined if traffic manager endpoint type is "external" (azure endpoint and nested endpoint being the other 2) and value is equal to AFD endpoint or custom domain.

If this is not the right premise, please help me with a pattern on how TM and AFD can be combined, and I will correlate using ARG.

image

AFD-10 - Enable the WAF
The query shows AFDs with no security policies or where there are no managed rules (which will automatically include standard skus).
image

AFD-11 - Disable health probes when there is only one origin in an origin group

Query shows AFDs with single origin and active health probe.
image

## As part of this Pull Request I have

- [ x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [ x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [ x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [ x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [ ] Ensured PR tests are passing
- [x ] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Review by ejhenry — COMMENTED** [review]
Thanks for the contribution @didayal-msft. Please include screenshots of your test results for each query.

**Comment by didayal-msft** [comment]
> Thanks for the contribution @didayal-msft. Please include screenshots of your test results for each query.

Updated original post with screenshots

**Comment by ejhenry** [comment]
@Azure/aprl-networking please review and compare with #318

**Comment by ejhenry** [comment]
@Azure/aprl-networking please review

**Comment by oZakari** [comment]
Hey @didayal-msft, just checking as I see this PR is in a draft state, are you going to be adding stuff or can you set the PR ready to review if applicable.

**Review by JefferyMitchell — APPROVED** [review]

**Review by oZakari — APPROVED** [review]
@didayal-msft really nice work on these queries. I've just updated the summary table for the new queries but LGTM

**Pull request merged**
