### PR TITLE
ERGW-4 Monitoring Alert Kusto Queries

### PR DESCRIPTION
**Pull request by jchancellor-ms**
# Overview/Summary
This is the kusto queries for the ERGW-4 APRL.  It contains 7 kql files representing the various monitoring requirements for ExpressRoute Gateways.
## This PR fixes/adds/changes/removes

1. Add 7 file ergw-4.1.kql, ergw-4.2.kql, ergw-4.3.kql, ergw-4.4.kql, ergw-4.5.kql, ergw-4.6.kql, ergw-4.7.kql

### Breaking Changes

1. removes the existing ergw-4.kql file

## As part of this Pull Request I have

- [x ] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [ x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [ x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [ x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [ x] Ensured PR tests are passing
- [x ] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- [ x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Comment by jchancellor-ms** [comment]
ergw-4.1 evidence 
image

**Comment by jchancellor-ms** [comment]
ergw-4.2 evidence 
image

**Comment by jchancellor-ms** [comment]
ergw-4.3 evidence 
image

**Comment by jchancellor-ms** [comment]
ergw-4.4 evidence 
image

**Comment by jchancellor-ms** [comment]
ergw-4.5 evidence 
image

**Comment by jchancellor-ms** [comment]
ergw-4.6 evidence 
image

**Comment by jchancellor-ms** [comment]
ergw-4.7 evidence

**Comment by jchancellor-ms** [comment]
Because we used a different naming concept than the default ergw-4.kql, the link checks are failing as it needs to link to the original file.  I"ve added it back with a comment for now, but we can discuss tomorrow how best to handle having multiple kql files.

**Review by rodrigosantosms — APPROVED** [review]
LGTM

**Pull request merged**
