### PR TITLE
Updating Recommendations for General networking

### PR DESCRIPTION
**Pull request by maheshbenke**
# Overview/Summary

Updating Recommendations for General networking

## This PR fixes add Recommendations for General networking

1. *Updating Recommendations for General networking*

### Breaking Changes

NA

## As part of this Pull Request I have

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [ ] Ensured PR tests are passing
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Comment by maheshbenke** [comment]
Related to ADO Task : https://dev.azure.com/CSUSolEng/Well-Architected%20Framework/_workitems/edit/27230?src=WorkItemMention&src-action=artifact_link

**Review by lachaves — CHANGES_REQUESTED** [review]
@maheshbenke, a couple things. 
At first glance it seems the ARG queries are available. Maybe just add a "Work in Progress" or "To Be defined" label at the beginning of each query, before the "// Azure Resource Graph Query" line.

Also, for NW-1, at the end of the "Recommendation/Guidance" section there is the following line "For more information, see Cross-network connectivity." but its not clear what is meant with "see Cross-network connectivity". Is this supposed to be a link to some other section or web page?
Everything else is fine.

**Comment by maheshbenke** [comment]
@lachaves Updated description and query blocks as requested.

**Review by lachaves — APPROVED** [review]
Looks good to me.

**Pull request merged**
