### PR TITLE
Adding Tags to VM Queries in APRL

### PR DESCRIPTION
**Pull request by alisakina99**
In all the available queries in the Virtual Machines section (total 18/22) in APRL, I added "tags" that are associated with the VMs in question by the queries as a column in the results

Replace this with a brief description of what this Pull Request fixes, changes, etc.

Adds tags to existing VM queries

[AB#32174](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/32174) 

## This PR fixes/adds/changes/removes

1. adds tags to VM-2, 4-12, 14-20, 22 query files

## As part of this Pull Request I have

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [x] Ensured PR tests are passing
- [x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Review by oZakari — APPROVED** [review]
LGTM, thanks @alisakina99!

**Review by ejhenry — COMMENTED** [review]
Hi @alisakina99, please provide screenshots for evidence the queries are working as expected. Thanks!

**Comment by alisakina99** [comment]
@ejhenry do we need screenshots for all 18 query changes?

**Comment by ejhenry** [comment]
> @ejhenry do we need screenshots for all 18 query changes?

@alisakina99 yes, any change associated with an ARG query requires evidence of successful testing.

**Comment by alisakina99** [comment]
vm2
vm4
vm5
vm6
vm7
vm8
vm9
vm10
vm11
vm12
vm14
vm15
vm16
vm17
vm18
vm19
vm20
vm22

**Review by lachaves — APPROVED** [review]
LGTM.

**Comment by alisakina99** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Pull request merged**
