### PR TITLE
adds ala-1 query

### LINKED ISSUE #353: 🪲 Bug Report - ala-1 missing
## Describe the bug

The query for ALA-1 is missing. I am working on it.

### PR DESCRIPTION
**Pull request by ReneHezser**
# Overview/Summary

Adds the Resource Graph Query to check ala-1 recommendation.

## Related Issues/Work Items

- Fixes #353 

## This PR fixes/adds/changes/removes

1. Adds Resource Graph Query for ala-1 

### Breaking Changes

none

image

## As part of this Pull Request I have

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [x] Ensured PR tests are passing
- [x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Review by Dost2010 — APPROVED** [review]

**Review by ejhenry — COMMENTED** [review]
Thanks @ReneHezser. Do you think we can account for a scenario where the service health alerts for a subscription are separated across multiple alerts? For example, a separate alert for each event type.

**Comment by ReneHezser** [comment]
@ejhenry I like your way of thinking. That is possible. I can also imagine other scenarios.
As with other automated checks, this can only be an indicator of what we want to achieve. Get the Service Health Alerts. Configured alerts are only an indicator if the backend process picks them up and brings them to someone's attention.
Better a false alert than no alert at all. If this recommendation comes up in a review situation, you can talk about it or dismiss it.

**Comment by ejhenry** [comment]
> @ejhenry I like your way of thinking. That is possible. I can also imagine other scenarios. As with other automated checks, this can only be an indicator of what we want to achieve. Get the Service Health Alerts. Configured alerts are only an indicator if the backend process picks them up and brings them to someone's attention. Better a false alert than no alert at all. If this recommendation comes up in a review situation, you can talk about it or dismiss it.

I guess I'm not understanding. I set up two Service Health alerts in my test sub, one covers Planned Maintenance and the other covers the three remaining event types. With this configuration the subscription is compliant with the recommendation. The query, however, is returning the subscription as non-compliant with the recommendation. This is the problem I think we still need to address.

**Comment by ReneHezser** [comment]
@ejhenry The check is now PowerShell, as it was easier to verify all event types have been covered.

**Comment by ejhenry** [comment]
> @ejhenry The check is now PowerShell, as it was easier to verify all event types have been covered.

Thanks for working on this and your effort is appreciated @ReneHezser! The PowerShell and CLI automation options have been removed from APRL. We are currently only using ARG for recommendations.

**Pull request closed without merging**
