### PR TITLE
Updated AVS to Verified and added dependency recommendations

### PR DESCRIPTION
**Pull request by michielvanschaik**
# Overview/Summary

Updated AVS to Verified after sign-off and added dependency recommendations

## This PR fixes/adds/changes/removes

1. AVS recommendations set to Verified
2. Dependency recommendations added for AVS

## As part of this Pull Request I have

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [x] Ensured PR tests are passing
- [x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Review by ejhenry — APPROVED** [review]
LGTM

**Comment by sblair01** [comment]
@ejhenry @oZakari @michielvanschaik  is out of the office, and I haven't had a chance to review this and I have some modifications. I will open a separate PR.

**Comment by sblair01** [comment]
@michielvanschaik per discussion with Prasad, please remove ERC, ERGW recommendations as they are referenced in AVS-10. Let's keep ERCON[1,2] for now.

**Comment by sblair01** [comment]
@ejhenry @oZakari Michiel is out. Please approve this PR for AVS in his absence instead: https://github.com/Azure/Azure-Proactive-Resiliency-Library/pull/442

**Comment by oZakari** [comment]
Closing as replaced by #442

**Pull request closed without merging**
