### PR TITLE
Verified queries with PG Sai Kondapalli and Harmeet Singh

### PR DESCRIPTION
**Pull request by mspetroula**
# Overview/Summary

Changing the State of the MySQL and PostgreSQL queries to Verified after reviewing with PG

## Related Issues/Work Items

Replace this with a list of related GitHub Issues and/or ADO Work Items (Internal Only)

- To associate a GitHub Issue, use a [key word](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) preceded with the GitHub issue number.
- To associate an ADO Work Item, use the key word `AB#` succeeded with the [ADO Work Item ID](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## This PR fixes/adds/changes/removes

1. MySQL _index.md from Preview to Verified
2. PostgreSQL _index.md from Preview to Verified

### Breaking Changes

1. *Replace me*
2. *Replace me*

## As part of this Pull Request I have

- [ X] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [ X] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [X ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [ X] Ensured PR tests are passing
- [X ] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- 
image
image

- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Comment by ejhenry** [comment]
@mspetroula thanks for the contribution. Can you update your PR to only include the edits to the two files you want to update? The PR currently has 633 files changed.

**Comment by mspetroula** [comment]
@ejhenry only 2 modified files are now in the pull request please verify.

**Comment by oZakari** [comment]
LGTM 👍🏼

**Review by oZakari — APPROVED** [review]

**Review by tksh164 — APPROVED** [review]
LGTM👍

**Pull request merged**
