### PR TITLE
ACR: Remove CR-4 and re-number CR items

### PR DESCRIPTION
**Pull request by ibersanoMS**
# Overview/Summary

Removed CR-4 since it is not applicable to resiliency and re-numbered items. No query changes.

## This PR fixes/adds/changes/removes

1. Removes CR-4
2. Re-numbers CR items - it looked like the numbering was off by one before I did the removal so some of them changed by 2 places instead of one place.

### Breaking Changes
None

## As part of this Pull Request I have

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [x] Ensured PR tests are passing
- [x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Review by ejhenry — COMMENTED** [review]
Thanks @ibersanoMS. We're not re-using recommendation IDs, so no need to re-number any of the other recommendations. We found that changing IDs was resulting in a lot of confusion for users and some of the other teams that consume from APRL.

**Comment by ibersanoMS** [comment]
@ejhenry Ah gotcha - should I revert the re-numbering?

**Comment by ejhenry** [comment]
Yes, please revert the re-numbering. Thanks!

**Review by ejhenry — APPROVED** [review]
LGTM 👍

**Review by oZakari — APPROVED** [review]
LGTM 👍🏼

**Pull request merged**
