### PR TITLE
Add Tags to Cosmos DB ARG Queries in APRL

### PR DESCRIPTION
**Pull request by alisakina99**
In all the available queries in the Container Registries section (total 3/9) in APRL, I added "tags" that are associated with the Cosmos DBs in question by the queries as a column in the results

## Related Issues/Work Items

Replace this with a list of related GitHub Issues and/or ADO Work Items (Internal Only)

[AB#32747](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/32747)
https://dev.azure.com/CSUSolEng/Well-Architected%20Framework/_workitems/edit/32747/

## This PR fixes/adds/changes/removes

1. Cosmos-1
2. Cosmos-3
3. Cosmos-5

## As part of this Pull Request I have

[X ] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
[X ] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
[X ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
[X ] Ensured my code/branch is up-to-date with the latest changes in the main [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
[X ] Ensured PR tests are passing
 Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
[X ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

cosmos-1
cosmos-3
cosmos-5

### CODE REVIEW

**Comment by alisakina99** [comment]
The deletion of the postgreSQL file was a mistake- I was trying to create a new PR for a separate task but the edit got merged with the edits of this PR. If you're able to reverse that before merging, please do.

P.S. What is the way to properly create two PRs for two separate tasks?

**Comment by oZakari** [comment]
> The deletion of the postgreSQL file was a mistake- I was trying to create a new PR for a separate task but the edit got merged with the edits of this PR. If you're able to reverse that before merging, please do.
> 
> P.S. What is the way to properly create two PRs for two separate tasks?

Hey @alisakina99, feel free to ping me when you have 15 minutes and we can remove the unintended commit as well as go through creating separate PRs.

**Review by oZakari — APPROVED** [review]
LGTM, thanks @alisakina99

**Review by ejhenry — APPROVED** [review]
LGTM thanks @alisakina99

**Pull request merged**
