### PR TITLE
Added avd-3.kql

### PR DESCRIPTION
**Pull request by yahanda**
# Overview/Summary

Added ARG query for AVD-3.

## Related Issues/Work Items

Replace this with a list of related GitHub Issues and/or ADO Work Items (Internal Only)

None

## This PR fixes/adds/changes/removes

1. Added ARG query for AVD-3

### Breaking Changes

None

## As part of this Pull Request I have

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [ ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [x] Ensured PR tests are passing
- [x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Comment by ejhenry** [comment]
Thanks for the contribution @yahanda! Please include a screenshot of the successful testing of your query.

**Comment by yahanda** [comment]
Hi @ejhenry, thank you for your comment. I updated the _index.md for AVD. Also, the screenshot is as follows - use INNER JOIN to exclude VMs that are not session hosts.

image

**Review by oZakari — APPROVED** [review]

**Comment by oZakari** [comment]
@Azure/aprl-avd please review.

**Review by moisesjgomez — APPROVED** [review]

**Comment by oZakari** [comment]
Hey @yahanda, thank you for your work on this. However, I'm going to closing this as in the latest AVD PR, the AVD team has removed the recommendation from their page.

**Pull request closed without merging**
