### PR TITLE
Updated VPNG-* recommendations

### PR DESCRIPTION
**Pull request by fguerri**
# Overview/Summary

This PR
- provides updated wording for VPNG-1, VPNG-4
- deletes VPNG-3 (the recommendation is applicable to gateways of type ER, not VPN)
- adds VPNG-7, including ARG query

## Related Issues/Work Items
NA

## This PR fixes/adds/changes/removes

1. Fixes: VPNG-1, VPNG-4
2. Removes: VPNG-3
3. Adds: VPNG-7

### Breaking Changes

NA

## As part of this Pull Request I have

- [X] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [X] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [X] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [X] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [X] Ensured PR tests are passing
- [X] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- [NA] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Review by ejhenry — COMMENTED** [review]
Thanks @fguerri! Please include a screenshot of the results of your query testing.

**Review by tksh164 — COMMENTED** [review]
@fguerri - Could you change the column names in the query? because current column names are not aligned to the standards for recommendations.

- [Azure Resource Graph (ARG) Queries - Contribution guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing/#azure-resource-graph-arg-queries)
> 6. ARG query columns name returned should only include the following:

**Comment by fguerri** [comment]
@ejhenry  pls find the screenshots below.

1) Active-Active, zone-redundant VPN gateway associated with zonal PIPs:

image


2) Active-Passive, zone-redundant VPN gateway associated with zonal PIP:

image

**Comment by fguerri** [comment]
@tksh164 fixed output formatting as per contribution guide

**Review by rodrigosantosms — CHANGES_REQUESTED** [review]
@fguerri  please do not add links in the "Guidance" section as this can break the integration with other tools. All reference links shoud be under the "Resouces" section.

**Comment by JefferyMitchell** [comment]
@aybatra

**Comment by fguerri** [comment]
As concurrent changes have created conflicts, I am closing this PR and submitting a new one.

**Pull request closed without merging**
