### PR TITLE
Expressroute gateway - initial PR

### PR DESCRIPTION
**Pull request by ehaslett**
# Overview/Summary

APRL guidance for ExpressRoute Gateway

## This PR fixes/adds/changes/removes

1. Adds section under Network for ExpressRoute Gateway

### Breaking Changes

1. *Replace me*
2. *Replace me*

## As part of this Pull Request I have

- [x ] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [x ] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [x ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [x ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [x ] Ensured PR tests are passing
- [x ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Review by lachaves — CHANGES_REQUESTED** [review]
@ehaslett, everything looks fine. I would just update the table with the recommendations that have the ARG query and those that dont.

**Comment by ehaslett** [comment]
> @ehaslett, everything looks fine. I would just update the table with the recommendations that have the ARG query and those that dont.

@lachaves  - changes made, please review when you can. Thank you!

**Review by lachaves — APPROVED** [review]
LGTM.
Ethan, for EXRGW4 and 5, if the ARG queries are ready we could update the table, as with EXRGW1 which indicates "Yes" for ARG query. Not sure if 4 and 5 are still work in progress.

**Comment by ehaslett** [comment]
> LGTM. Ethan, for EXRGW4 and 5, if the ARG queries are ready we could update the table, as with EXRGW1 which indicates "Yes" for ARG query. Not sure if 4 and 5 are still work in progress.

4 and 5 are still in progress. They function but are not perfect, so left as TBD.

**Pull request merged**
