### PR TITLE
Guidance and KQL query for asr-2 (Test Failover)

### PR DESCRIPTION
**Pull request by pedrocsousa**
# Overview/Summary

Guidance and KQL query for asr-2 (Perform a test failover on VMs protected with ASR.)

## Related Issues/Work Items

[AB#29840](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/29840)

## This PR fixes/adds/changes/removes

1. Guidance
2. KQL query

### Breaking Changes

N/a

## As part of this Pull Request I have

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [x] Ensured PR tests are passing
- [x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Review by oZakari — CHANGES_REQUESTED** [review]
Thanks for submitting this @pedrocsousa! There was a merge conflict and a broken link that I fixed, but other than that it looks good from a content perspective. 

The only thing we'll need before we can merge this is a screenshot of the query showing that it works and provides the correct result as you did for your other recently submitted PR.

**Comment by pedrocsousa** [comment]
> Thanks for submitting this @pedrocsousa! There was a merge conflict and a broken link that I fixed, but other than that it looks good from a content perspective.
> 
> The only thing we'll need before we can merge this is a screenshot of the query showing that it works and provides the correct result as you did for your other recently submitted PR.

Hi @oZakari! Please find below the screenshots proving it works. 

image

**Review by oZakari — APPROVED** [review]

**Comment by oZakari** [comment]
@ejhenry Can you please review when you get a chance?

**Review by ejhenry — APPROVED** [review]
LGTM 👍 Thanks @pedrocsousa!

**Pull request merged**
