### PR TITLE
Adding back AVS-1 and 2 with kusto and powershell queries

### PR DESCRIPTION
**Pull request by jchancellor-ms**
# Overview/Summary

Adds back AVS-1 and AVS-2 recommendations.  Includes a kusto query for AVS-1, and a powershell script for AVS-2

## This PR fixes/adds/changes/removes

1. Adds AVS-1 and AVS-2 Recommendation text
2. Creates a kusto query for AVS-1
3. Creates a powershell query for AVS-2

### Breaking Changes

1. None

## As part of this Pull Request I have

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [x] Ensured PR tests are passing
- [x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Review by michielvanschaik — APPROVED** [review]
No comments.

**Review by ejhenry — COMMENTED** [review]
Thanks @jchancellor-ms. Can you include screenshots of the results of your testing of the kql and powershell queries?

**Comment by jchancellor-ms** [comment]
AVS-2.  I couldn't get this in one screenshot so combined two of them - 
image

**Comment by jchancellor-ms** [comment]
@ejhenry - Please let me know if the attached screenshots include enough detail for evidence.

**Review by ejhenry — APPROVED** [review]
LGTM 👍

**Review by oZakari — APPROVED** [review]

**Pull request merged**
