### PR TITLE
ergw-1 kql update

### PR DESCRIPTION
**Pull request by jchancellor-ms**
# Overview/Summary

Initial release of the kusto for ERGW-1.  This query checks virtual network expressRoute gateways to determine if they have connections to expressRoute circuits with at least two peering locations.  It currently excludes gateways with 0 connections and expressRoute circuits that are used by baremetal services. (AVS, SAP, HSM, MSIT)

## This PR fixes/adds/changes/removes

1. Adds kusto query for APRL ERGW-1

## As part of this Pull Request I have

- [ x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [ x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [ x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [ x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [ x] Ensured PR tests are passing
- [ x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- [ x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Comment by jchancellor-ms** [comment]
Screen shot of output from query in an environment with both AVS and normal expressroute circuits. Data has been masked using internal names/subscriptions.
image

**Comment by jchancellor-ms** [comment]
I think logically it would make sense if for no other reason that customers would want to know where they are wasting money with unused Gateways.  However, purely from a resiliency perspective it would irrelevant as a gateway without connections is both minimally and maximally resilient.  In this case, it happens this way because the way I was able to hack around the baremetal circuit's not being included in the resource graph was to exclude cases where connections existed and but location details did not.

Let me see if I can figure out how to bring back the empty gateways while still excluding the baremetal circuits.
________________________________

**Review by oZakari — APPROVED** [review]
Well done, this looks like it was a bit of a beast to deal with.

**Comment by jchancellor-ms** [comment]
@maheshbenke and @oZakari  - I added logic to include gateways with 0 connections.  (evidence below) - Let me know if we can merge and close this one out.  Given the number of changes since the PR, I had to do an additional pull to sync by working branch.  If this causes issues let me know and I can submit a new PR.  
image

**Comment by ejhenry** [comment]
@jchancellor-ms can you also submit a PR to update the summary table in the index file to show that ergw-1 now has an ARG query?

**Pull request merged**
