### PR TITLE
add cr-9

### PR DESCRIPTION
**Pull request by ReneHezser**
# Overview/Summary

Add cr-9 recommendation

## Related Issues/Work Items

[AB#32799](https://dev.azure.com/CSUSolEng/12ba7e46-a92a-47f6-ad6a-fba0479234a7/_workitems/edit/32799)

## This PR fixes/adds/changes/removes

1. add resource grapth query for cr-9

### Breaking Changes

none

### testing

Tested with 4 container registries, where 2 had the admin user enabled.

image

image

## As part of this Pull Request I have

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [x] Ensured PR tests are passing
- [x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Review by oZakari — APPROVED** [review]
LGTM 👍🏼

**Review by ejhenry — COMMENTED** [review]
@ReneHezser the query looks good, thanks. Do you think we should reword the recommendation to align with the query? Perhaps something like "Disable the admin account when not in use"?

**Comment by ReneHezser** [comment]
> @ReneHezser the query looks good, thanks. Do you think we should reword the recommendation to align with the query? Perhaps something like "Disable the admin account when not in use"?

Thanks for bringing this up, as it is a thought I also had. I decided against it, as the query will find resources that match. Regardless of the meaning *is it good or bad I find them?*

This could be a topic for all queries. Personally, I like the documentation of the task of a query without evaluation and I think the current comment aligns with our [Automation Standards for Recommendations](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing/#azure-resource-graph-arg-queries)

**Review by oZakari — CHANGES_REQUESTED** [review]
Putting this 'request for changes' in to block the PR completion until @ReneHezser pushes his local branch back over the top due to issue I caused with his branch.

**Pull request closed without merging**
