### PR TITLE
Adding KQL for App Service And App Service Plans

### PR DESCRIPTION
**Pull request by motasem13**
wrote KQL queries to check App Service Recommendations

# Overview/Summary

i have wrote a queries for App Service Plans (1 ... 5) and Web App( 1 ... 6)

## Related Issues/Work Items

Replace this with a list of related GitHub Issues and/or ADO Work Items (Internal Only)

- To associate a GitHub Issue, use a [key word](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) preceded with the GitHub issue number.
- To associate an ADO Work Item, use the key word `AB#` succeeded with the [ADO Work Item ID](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## This PR fixes/adds/changes/removes

1. *Replace me*
2. *Replace me*
3. *Replace me*

### Breaking Changes

1. *Replace me*
2. *Replace me*

## As part of this Pull Request I have

- [ x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [x ] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [ x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [ ] Ensured PR tests are passing
- [x ] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

### CODE REVIEW

**Comment by motasem13** [comment]
ASP-1 - Migrate App Service to availability Zone Support 
image


ASP-2 - Use Standard or Premium tier 
image


ASP-3 - Avoid scaling up or down 
image


ASP-5 - Enable Autoscale/Automatic scaling to ensure adequate resources are available to service requests 
image

**Comment by motasem13** [comment]
App-1 - Enable diagnostics logging 
image

App-2 - Monitor Performance 
image


App-5 - Deploy to a staging slot 
image

App-6 - Store configuration as app settings 
image

**Review by ejhenry — COMMENTED** [review]
Thanks @motasem13! Can you also update the summary of recommendations table in the index files for each service to indicate ARG queries are available for the relevant recommendations?

**Review by ejhenry — DISMISSED** [review]
LGTM 👍 Thanks @motasem13!

**Comment by oZakari** [comment]
Hi @motasem13, thanks for all these fixes. Before I approve, could you please remove all of the .fix query files. Those were essentially created from previous PRs to give people a starting point. Since you either fixed them all or determined that the information was not possible to retrieve from resource graph then we can go ahead and delete them.

**Comment by motasem13** [comment]
@oZakari, I have removed the files

**Review by oZakari — APPROVED** [review]

**Pull request merged**
